# Generated by Django 3.1.7 on 2021-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small-125x150.png', max_length=500),
        ),
    ]
